language: python
script:
  - python test_arithmetic.py
  - python test_operandToken.py
  - python test_operatorToken.py
  - python test_shuntingYard.py
  - python test_stack.py
  - python test_stringInterpreter.py
